In [37]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn import metrics
from sklearn.metrics import confusion_matrix
#from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score, roc_curve

In [36]:
data=fetch_california_housing()
x=pd.DataFrame(data.data , columns=data.feature_names)
y=pd.DataFrame(data.target, columns=["Price"])
x=pd.DataFrame(x,columns=data.feature_names)
y=pd.DataFrame(y, columns=["Price"])

In [3]:
x

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32


In [4]:
y

,Price
0,4.526
1,3.585
2,3.521
3,3.413
4,3.422
...,...
20635,0.781
20636,0.771
20637,0.923
20638,0.847


In [5]:
x.shape

(20640, 8)

In [6]:
x.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
dtype: int64

In [7]:
y.isnull().sum()

Price    0
dtype: int64

In [8]:
scaler=StandardScaler()
x=scaler.fit_transform(x)
y=scaler.fit_transform(y)


In [9]:
x

array([[ 2.34476576,  0.98214266,  0.62855945, ..., -0.04959654,
         1.05254828, -1.32783522],
       [ 2.33223796, -0.60701891,  0.32704136, ..., -0.09251223,
         1.04318455, -1.32284391],
       [ 1.7826994 ,  1.85618152,  1.15562047, ..., -0.02584253,
         1.03850269, -1.33282653],
       ...,
       [-1.14259331, -0.92485123, -0.09031802, ..., -0.0717345 ,
         1.77823747, -0.8237132 ],
       [-1.05458292, -0.84539315, -0.04021111, ..., -0.09122515,
         1.77823747, -0.87362627],
       [-0.78012947, -1.00430931, -0.07044252, ..., -0.04368215,
         1.75014627, -0.83369581]], shape=(20640, 8))

In [10]:
y

array([[ 2.12963148],
       [ 1.31415614],
       [ 1.25869341],
       ...,
       [-0.99274649],
       [-1.05860847],
       [-1.01787803]], shape=(20640, 1))

1. Loaded the dataset from sklearn and change into a dataframe using pandas
2. Checked for null values in both dataframes x and y
3. Values in the dataset are varying in large scale so we used standard scaler

In [13]:
x1=x[['AveRooms']]
y1=y[['Price']]

In [14]:
x_train,x_test,y_train,y_test=train_test_split(x1,y1 ,test_size=0.2,random_state=42)

In [15]:
model=LinearRegression()
model

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [16]:
model.fit(x_train,y_train)
model

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [17]:
y_pred=model.predict(x_test)
y_pred


array([[1.97653709],
       [2.04156313],
       [1.96003112],
       ...,
       [2.21029436],
       [2.06072485],
       [1.96092798]], shape=(4128, 1))

In [18]:
y_test

,Price
20046,0.47700
3024,0.45800
15663,5.00001
20484,2.18600
9814,2.78000
...,...
15362,2.63300
16623,2.66800
18086,5.00001
2144,0.72300


In [19]:
lg_mae=metrics.mean_absolute_error(y_pred,y_test)
print(lg_mae)

0.8891490366373881


In [20]:
lg_mse=metrics.mean_squared_error(y_pred,y_test)
print(lg_mse)

1.2923314440807299


In [21]:
lg_rmse=metrics.root_mean_squared_error(y_pred,y_test)
print(lg_rmse)

1.1368075668646518


In [22]:
lg_r2Score=metrics.r2_score(y_pred,y_test)
print(lg_r2Score)

-27.092058513710466


***Linear Regression***
* This regression model analyse the train dataset and plot graph.
* It finds the intercept and slope of the graph.
* When we want to find the target value, this model calculate the result bu using the slope and intercept, try to plote the new value in to the graph.
* we used this model beacuse here we used AveRooms to predict Price,2 columns are present so linear regression is best beacuse it plots a linear graph(straight line).

In [23]:
x_train,x_test,y_train,y_test=train_test_split(x,y ,test_size=0.2,random_state=42)

In [24]:
dtmodel=DecisionTreeRegressor()
dtmodel

,criterion,'squared_error'
,splitter,'best'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,None
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,ccp_alpha,0.0


In [25]:
dtmodel.fit(x_train,y_train)
dtmodel

,criterion,'squared_error'
,splitter,'best'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,None
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,ccp_alpha,0.0


In [26]:
y_pred_dt=dtmodel.predict(x_test)
y_pred

array([[1.97653709],
       [2.04156313],
       [1.96003112],
       ...,
       [2.21029436],
       [2.06072485],
       [1.96092798]], shape=(4128, 1))

In [27]:
y_test

,Price
20046,0.47700
3024,0.45800
15663,5.00001
20484,2.18600
9814,2.78000
...,...
15362,2.63300
16623,2.66800
18086,5.00001
2144,0.72300


In [28]:
mae=metrics.mean_absolute_error(y_pred_dt,y_test)
print(mae)

0.45810772044573644


In [29]:
mse=metrics.mean_squared_error(y_pred_dt,y_test)
print(mse)

0.5055271332937743


In [30]:
rmse=metrics.root_mean_squared_error(y_pred_dt,y_test)
print(rmse)

0.7110043131330318


In [41]:
r2Score=metrics.r2_score(y_test,y_pred_dt)
print(r2Score)

0.6142218637937015


   ***Decision Tree Regressor***
* It make the dataset like a tree and analysing condition at each depth predict the value.
* Here we use decision tree regressor because we have to predict price by analysing more than 1 feature.
  